### ISSUE TITLE
Add ability to parameterize reclaim policy for ES data nodes

### ISSUE THREAD

**Issue by snsumner** [upmc-enterprises/elasticsearch-operator#113]
For demo purposes it would be nice to be able to switch the reclaim policy to Delete currently its hardcoding to Retain:

https://github.com/upmc-enterprises/elasticsearch-operator/blob/6b47b2edb60c6682eef4f9488bc9d8bdfb8be66d/pkg/processor/processor.go#L212

**Comment by snsumner** [comment]
How do you utilize this fix?

**Comment by stevesloka** [comment]
There's a new `volume-reclaim-policy` on the storage option in the CRD. You can add that and set the policy to `Retain` or `Delete`.
