### ISSUE TITLE
Use Kubernetes CronJobs instead of cron tasks inside pod containers.

### ISSUE THREAD

**Issue by pires** [upmc-enterprises/elasticsearch-operator#12]
This is becoming beta in 1.6 so perhaps it's a good time to adopt it.

An example can be found at https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-curator.yaml.

**Comment by stevesloka** [comment]
Oh that's very cool, I didn't know about Curator. I'll look to get this integrated!

**Comment by pires** [comment]
Curator is one thing, using CronJobs is another ;)

**Comment by stevesloka** [comment]
This has been implemented in #68
