### ISSUE TITLE
Error: "no matches for enterprises.upmc.com" when creating example on minikube

### ISSUE THREAD

**Issue by selvik** [upmc-enterprises/elasticsearch-operator#124]
Hello,

I am using minikube version 0.18 and Kubernetes version 1.8.5 on OS X.

The first step of kubectl create of example/controller.yaml completes successfully. However the second step (below) returns with the following error:

`$ kubectl create -f https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/example/example-es-cluster-minikube.yaml`

`error: unable to recognize "https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/example/example-es-cluster-minikube.yaml": no matches for enterprises.upmc.com/, Kind=ElasticsearchCluster`

Could you please let me know of anything else I need to do before these two steps (other than creating the namespace "operator") ?

Any hints to troubleshoot would be awesome! Thank you.

**Comment by stevesloka** [comment]
Could you do a: `kubectl get crd` and see if there are types in there for elastic? Also, could look at the logs from the operator when it first starts up to see if there are errors there. One of the first things it does is create it's own CRD, if that fails then the next step you're trying will as well.

**Comment by selvik** [comment]
Thanks] you very much for the response. `get crd` does not return any resources. Here are the errors from the pod.  It seems to be some RBAC related issue. Does this operator need some roles to be customized?

```
[admin@selhx1 ~]$ kubectl get crd
No resources found.
[admin@selhx1 ~]$ kubectl get pods
NAME                                      READY     STATUS             RESTARTS   AGE
elasticsearch-operator-6bc475878b-mcprr   0/1       CrashLoopBackOff   159        13h

[admin@selhx1 ~]$ kubectl logs elasticsearch-operator-6bc475878b-mcprr
time="2017-12-20T15:53:42Z" level=info msg="elasticsearch operator starting up!" 
time="2017-12-20T15:53:42Z" level=info msg="Using Variables:" 
time="2017-12-20T15:53:42Z" level=info msg="   baseImage: upmcenterprises/docker-elasticsearch-kubernetes:5.3.1" 
time="2017-12-20T15:53:42Z" level=info msg="Using InCluster k8s config" 
panic: customresourcedefinitions.apiextensions.k8s.io "elasticsearchclusters.enterprises.upmc.com" is forbidden: User "system:serviceaccount:default:default" cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope

goroutine 1 [running]:
github.com/upmc-enterprises/elasticsearch-operator/pkg/k8sutil.(*K8sutil).CreateKubernetesCustomResourceDefinition(0xc4203b0980, 0x0, 0x0)
	/Users/slokas/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/k8sutil/k8sutil.go:291 +0x6ec
github.com/upmc-enterprises/elasticsearch-operator/pkg/controller.(*Controller).init(0xc4205e5e48, 0x0, 0xc4205e5d90)
	/Users/slokas/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/controller/controller.go:69 +0x2e
github.com/upmc-enterprises/elasticsearch-operator/pkg/controller.(*Controller).Run(0xc4205e5e48, 0x1531920, 0x6)
	/Users/slokas/godev/src/github.com/upmc-enterprises/elasticsearch-operator/pkg/controller/controller.go:58 +0x2f
main.Main(0x124c133)
	/Users/slokas/godev/src/github.com/upmc-enterprises/elasticsearch-operator/cmd/operator/main.go:111 +0x681
main.main()
	/Users/slokas/godev/src/github.com/upmc-enterprises/elasticsearch-operator/cmd/operator/main.go:144 +0x22
[admin@selhx1 ~]$ 
```

**Comment by selvik** [comment]
After giving cluster-admin privileges to the "default" service account in the "default" namespace, the operator started working correctly.

```kubectl create clusterrolebinding cluster-admin-binding-2   --clusterrole=cluster-admin  --user=system:serviceaccount:default:default```

Was I supposed to do this?  Would you know what all changes need to be made if I wanted to run the operator as a specific user with these elevated privilege? (I would prefer to not give default service accounts cluster-admin privileges :-))

**Comment by stevesloka** [comment]
The example controller includes the proper RBAC rules. Can you maybe create it again (https://github.com/upmc-enterprises/elasticsearch-operator/blob/master/example/controller.yaml) and see if any other errors pop up?

**Comment by stevesloka** [comment]
Let me know if you see any issues with the RBAC rules and please reopen if you do, I'll close for now.
