### ISSUE TITLE
deleting the cluster causes secrets to be removed

### ISSUE THREAD

**Issue by ethanwinograd** [upmc-enterprises/elasticsearch-operator#127]
Doing a kubectl delete -f on the es-cluster.json removes the secrets that are used to mount the certs.
I think this is being done by the operator, because new secrets (with new certs) are being generated when the create is subsequently called on that controller spec.  

This presents a problem for client applications including searchguard sgadmin.

**Comment by stevesloka** [comment]
Yes, this is the current behavior. The thinking is, if you delete the cluster then the secrets are no longer valid and clients have nothing to talk to sine the cluster was deleted.

**Comment by ethanwinograd** [comment]
thats cool except that the operator then creates its own secrets which are out of sync with the clients.  the cluster gets recreated with the operator-created secrets and the clients cant resolve the rootca.  worse if you are using truststore and keystore to do searchguard admin, because they cant handshake at all. (different truststore and keystore).
this kind of ties back to the editing tpr problem, because there is no other way to modify the cluster than to recreate it with updated settings.

**Comment by stevesloka** [comment]
You can absolutely edit the cluster by mutating the TPR and the operator will update the cluster accordingly.  There shouldn't be a normal maintenance mode where you are deleting and recreating unless you actually want a new cluster.

Let's chat about it next week, I may be in town.

**Comment by stevesloka** [comment]
Hey @ethanwinograd, I added a param to allow you to set if secrets should be kept when a cluster is deleted. See: https://github.com/upmc-enterprises/elasticsearch-operator#customresourcedefinition
