### ISSUE TITLE
Init containers syntax with annotations is deprecated in Kubernetes 1.8

### ISSUE THREAD

**Issue by komljen** [upmc-enterprises/elasticsearch-operator#129]
The operator is using the old syntax for init containers https://github.com/upmc-enterprises/elasticsearch-operator/blob/master/pkg/k8sutil/deployments.go#L138.

And if we take a look here
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

"There is a new syntax in Kubernetes 1.6, although the old annotation syntax still works for 1.6 and 1.7. The new syntax must be used for 1.8 or greater. "

I tried to run the operator on Kubernetes 1.8 on minikube, but ES nodes will not start with this error `max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

1.7 is working fine.

**Comment by stevesloka** [comment]
The latest release should have the new syntax, I did have issues running on minikube with xhyve on OSX. Using virtual box was fine. 

Can you confirm you have the latest release of the operator?

**Comment by komljen** [comment]
Ah, I just saw that there is the new version. I'm using 0.0.9. I will try with 0.0.10 and if everything is ok I will close this issue.

**Comment by komljen** [comment]
Everything works with 0.0.10 release. Thanks

**Comment by stevesloka** [comment]
Awesome thanks! 😀
