### ISSUE TITLE
scaling existing pods

### ISSUE THREAD

**Issue by ethanwinograd** [upmc-enterprises/elasticsearch-operator#130]
It is not possible to edit the ElasticsearchCluster type, and so scaling the number of pods via editing the deployment descriptor or statefulsets result in the operator resetting the number back to the number specified in the cluster definition json file.  

Is there a way around this?

**Comment by stevesloka** [comment]
You should edit the TPR, then the operator will scale accordingly.

**Comment by ethanwinograd** [comment]
maybe its the version of kubernetes we are on but I dont think it is possible to edit the tpr.

**Comment by ethanwinograd** [comment]
ok you can close this, apparently its fixed in 1.6 and we are not there yet.

**Comment by stevesloka** [comment]
Scaling should work at any version, that was the first thing implemented. Please reopen if you continue to see issues.
