### ISSUE TITLE
Declare variable for busybox image

### ISSUE THREAD

**Issue by wadeholler** [upmc-enterprises/elasticsearch-operator#139]
As far as I can tell - Inclusion of k8sutil - introduces a dependency on busybox.  This declaration does not appear to have a variable for the location of the busybox image.  Deploying a cluster with this operator fails in disconnected environments that only have a private registry.

Suggestion: Update with a variable for the location of the busybox image, like has been done for the other ( elasticsearch, kibana, cerebro, etc ) images.

**Comment by stevesloka** [comment]
@wadeholler is it just for visibility? This image is one that I'm not sure should be overridden by users since it's a "system" level container. We're going to be switching to a daemonset soon, but will still use this image. 

Would a better call-out in the readme / release notes help?

**Comment by chandu1221** [comment]
@stevesloka I am facing the similar issue of pulling busybox image from daemonset.

![image](https://user-images.githubusercontent.com/7453460/37570771-5589cc34-2aca-11e8-86c8-18f8e59827fd.png)

We do pull images only from private registries and @wadeholler 's suggestion works well for our scenarios too. Also it would be great if namespace can be configurable instead of defaulting.

**Comment by pieterlange** [comment]
It's useful when you don't let your cluster connect directly to the internet and/or run arbitrary docker hub images. :+1:

> Also it would be great if namespace can be configurable instead of defaulting.
Please open a separate issue for that with a bigger description @chandu1221

**Comment by stevesloka** [comment]
Ahh I understand now, we can make this a parameter.

**Comment by wadeholler** [comment]
@stevesloka - my apologies for the delay.  other folks are spot on.  At our site we don't connect / pull from public registry.  Thank you!

**Comment by Tharun-Sabbu** [comment]
Hello guys, any update on this issue. We have our own private docker registry and can't make the master and data nodes run because of the busybox image.

**Comment by Tharun-Sabbu** [comment]
When is the next release going to be with busybox image as a variable, currently I had to use the following command to overcome the issue:  kubectl set image ds elasticsearch-operator-sysctl  sysctl-conf=privaterepo/busybox:latest && kubectl get po -l k8s-app=elasticsearch-operator -o name | cut -d"/" -f2 | while read p;do kubectl  delete po $p;sleep 5;done

**Comment by Cynerva** [comment]
Any chance of this making it out to a stable release? I have a need for this option but it looks like it still hasn't been released.
