### ISSUE TITLE
How safe is the data if I change disk size and re-deploy

### ISSUE THREAD

**Issue by thomascooper** [upmc-enterprises/elasticsearch-operator#148]
Team,

I need some advice, I have deployed a 7 node cluster (2 clients, 2 masters, 3 data nodes). My data-volume-size is 30Gi, after loading our initial data set, my store.size is 41gb and pri.store.size is 21gb, I am not sure what the best approach is here going forward, in order to not risk losing the my data. we are using GKE so we do not have snapshot enabled. Here are the 3 options i see

1.) spin up a new cluster with larger disk-sizes, use elasticdump to move data to the new instance, retire the old

2.) change the disk size and redeploy, this would only work if the controller made sure each re-deployed pod was fully in-sync before starting the next

3.) manually install repository-gcs and create a snapshot to gcp, then redeploy, manually repository-gcs again and run a restore

Any advice on which way i should proceed? My initial thought is option 3, but i have not yet looked into installing a plugin into a running upmc cluster.

**Comment by stevesloka** [comment]
Hey @thomascooper I think your best bet is to redeploy. Ideally, there would be a way to spin up larger data nodes and be able to roll through those and migrate your data but today do not have the capability for that today.

I am working on GKE snapshots, but still in progress.

**Comment by stevesloka** [comment]
Let me know if you have any further questions, I hope to get this operator to a place where it will handle these bits for you, that's really the point. Please re-open if you have further questions.
