### ISSUE TITLE
Operate clusters in any namespace

### ISSUE THREAD

**Issue by pst** [upmc-enterprises/elasticsearch-operator#15]
Currently it seems, the operator is only searching and listing for clusters that are in the same namespace as the operator.

https://github.com/upmc-enterprises/elasticsearch-operator/blob/master/util/k8sutil/k8sutil.go#L56

What I'm currently doing is deploying all my operators into one namespace but allow the managed clusters to be deployed to any namespace. I believe this is beneficial, because it allows to have one operator to operate seperate clusters for different services or environments like e.g. staging and production.

**Comment by stevesloka** [comment]
Yeah right now it uses the namespace the operator is deployed to  (https://github.com/upmc-enterprises/elasticsearch-operator/blob/master/util/k8sutil/k8sutil.go#L53) as the same place where the cluster will be sent. It also only allows for 1 ES cluster per k8s cluster as well. 

I'd get this on a list to make better. Thanks!

**Comment by stevesloka** [comment]
This is complete in #68
