### ISSUE TITLE
PersistentVolumeClaim is not bound: "es-data-es-data-example-es-cluster-hostpath-storage-0"

### ISSUE THREAD

**Issue by Shifter2600** [upmc-enterprises/elasticsearch-operator#154]
Kubernetes 1.9

I used the examples as listed in master
controller.yaml
example-es-cluster-hostpath.yaml
hostpath-sc.yaml
as is
I am getting this error.
PersistentVolumeClaim is not bound: "es-data-es-data-example-es-cluster-hostpath-storage-0"
Is the example missing another YAML for the PVC?

**Comment by Shifter2600** [comment]
I think I am onto something looks like hostpath is Will not work in a multinode environment. 
I have a baremetal 5 node cluster. I guess there is no way to use the local drives in my case. 
Would you suggest a NSF Setup and if so could you let me know what would need to change in the es-cluster-??? and what a new nsf-sc.yaml would look like? Thanks

**Comment by Shifter2600** [comment]
After some heavy googling I have came to this as a possible solution for local store for Baremetal Clusters Released in Kubernetes 1.9..Volume Topology-aware Scheduling

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-topology-scheduling.md 

This looks promising for the issue of local PV for multi node K8's  Would the current operator take into account this Bound PVC Enforcement for Node Scheduling.

**Comment by Shifter2600** [comment]
Thanks, Ya I am currently looking at the NSF vol option but the issue will be performance. Where as the solution in the link would allow the local storage in Multi Node Clusters.

**Comment by stevesloka** [comment]
Awesome! Let me know if you need more help or have questions, just re-open. =)

**Comment by iroller** [comment]
Hi @stevesloka. Could you elaborate a little on why local `hostPath` storage will not work for multi-node ElasticSearch cluster?
