### ISSUE TITLE
app labels and service names

### ISSUE THREAD

**Issue by Shifter2600** [upmc-enterprises/elasticsearch-operator#158]
I have been struggling now for a month to get a loadbalancer connected to Kibana and Elasticsearch. 
Any help would be appreciated. 
I am running Kubernetes on Rancher 2.0 on baremetal I have everything green and running fine locally but I can't get a LB to connect to the services so I can access them externally. 

The only hang up is what does the LB service need to be in order to connect to the Services spun up from the ES operator.  I have seen references to app labels in selector but I do not believe your Example setup has labels in place. 

Anyone have a example Config that is working for a LB service?

**Comment by stevesloka** [comment]
You'll want to use the service targeting the client nodes, they are your entry points. 

I've setup load balancers before without issue. Can you access Elastic or Kibana via services inside the cluster ok?

**Comment by Shifter2600** [comment]
I believe they are running but I am unable to Curl or connect to them locally because of the Rancher/K8s setup. I have 5 nodes all running RancherOS.... I did check the Logs and both Kiabana and ES in the logs look like they are UP. 
kubectl describe pods/es-client-example-es-cluster-f55fc74d7-v45tn -n operator 
does show state of running
kubectl describe pods/kibana-example-es-cluster-59c576bd69-9cljf -n operator
is running as well but I see an issue where 
Unable to revive connection: https://elasticsearch-example-es-cluster:9200/"}
and ES logs show
publish_address {10.233.64.8:9200},bound_addresses {0.0.0.0:9200}

But even with this connection between the 2 being an issue I should be able to still connect to the Kibana with a LB.

**Comment by Shifter2600** [comment]
I feel I am getting closer to a solution. For the LoadBalancer service. Where does it need to be and what selector do I need to use based on what the Operator is using for Labels?

**Comment by stevesloka** [comment]
The service is already created for you by the operator. Mine is called `elasticsearch-example-es-cluster` since my cluster name is `example`. 

The problem you may be looking for is that (by default) the type is `ClusterIP`. You'll need to manually for now update the type to `NodePort` or `LoadBalancer` if you were on a cloud.

**Comment by stevesloka** [comment]
Hey @Shifter2600 is this still an issue for you?
