### ISSUE TITLE
services created are different than what's on README

### ISSUE THREAD

**Issue by wjimenez5271** [upmc-enterprises/elasticsearch-operator#166]
I seem to be missing the "elasticsearch" service that is listed on the readme towards the end where you document the expected results after deploying. It seems the operator is creating a different service that listens on port `9200` called `elasticsearch-es-cluster`:

```
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
svc/elasticsearch-discovery-es-cluster   ClusterIP   10.43.16.139    <none>        9300/TCP   3m
svc/elasticsearch-es-cluster             ClusterIP   10.43.17.6      <none>        9200/TCP   3m
svc/es-data-svc-es-cluster               ClusterIP   10.43.213.106   <none>        9300/TCP   3m
```

I do happen to already have a service called "elasticsearch" in another namespace (not related to this operator), but I didn't see any errors in the operator log so it seemed it deployed as expected.

When I try to access that service through an ingress I get a HTTP/502.

**Comment by wjimenez5271** [comment]
Also may be worth noting that I specified the operator to only deploy to one AWS AZ:

```
  zones:
  - us-west-2c
```

**Comment by stevesloka** [comment]
Hey @wjimenez5271, there's a disconnect in the readme. The ES cluster service is `elasticsearch` + `<cluster-Name` so in your case `elasticsearch-es-cluster` is the service you'd want to use to access the cluster.

**Comment by wjimenez5271** [comment]
Thanks for the quick response, I created a PR for the README, hope that helps
