### ISSUE TITLE
Restore from snapshot?

### ISSUE THREAD

**Issue by montyz** [upmc-enterprises/elasticsearch-operator#177]
The readme mentions 

> Elasticsearch can snapshot it's indexes for easy backup / recovery of the cluster

but I don't see instructions on how to restore from a snapshot. Does the operator get involved in the restore operation, or is the standard practice to first bring up an empty cluster, and then restore it with a curl command?

**Comment by stevesloka** [comment]
Thanks @pieterlange! As mentioned right now the idea is to restore as mentioned previously manually. 

If interested in the CRD path, please re-open & post some use cases to help prioritize. Thanks!
