### ISSUE TITLE
debugging snapshots

### ISSUE THREAD

**Issue by montyz** [upmc-enterprises/elasticsearch-operator#180]
I set up snapshots to be run hourly, but nothing is showing up in my s3 bucket. I did apply the permissions like the instructions said. I don't see anything in the logs for the pods regarding s3. Where would I look to further debug this?

**Comment by gianrubio** [comment]
What version are you using? ELK v6.0 had changed apis had requiring changes in the elasticsearch-cron image, I addressed a PR #174 to fix that.

**Comment by montyz** [comment]
Ah, I didn't realize I needed to look at the operator logs. Yeah, I see the messages there you described in #174.
