### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by etspaceman** [upmc-enterprises/elasticsearch-operator#183]
Hey There - 

Was hoping to leverage some of your changes made in the master branch with some testing. Unfortunately it looks like there's no "latest" tag in dockerhub for me to use. I attempted to fork/build myself with little luck. 

Would it be possible to release a new tag or expose a latest tag?

**Comment by stevesloka** [comment]
Hey @etspaceman yes we're do for a release. I know @komljen is testing one more PR and once that's complete we'll probably merge that and then cut it.

**Comment by komljen** [comment]
Yeah, this is the PR we want in new release https://github.com/upmc-enterprises/elasticsearch-operator/pull/175

**Comment by stevesloka** [comment]
Release is out! v0.0.12
