### ISSUE TITLE
The sysctl-deamonset is run in "default" namespace, not same as the operator.

### ISSUE THREAD

**Issue by ehvattum** [upmc-enterprises/elasticsearch-operator#197]
https://github.com/upmc-enterprises/elasticsearch-operator/blob/b3a11249593f5118e83cd92b10b72841c5e87dce/pkg/controller/controller.go#L74

When the operator is deployed with helm, the sysctl-deamonset is started in "default" namespace.
This deamonset is also not receiving the usual helm-metadata, tying the deployment of this deamonset to the helm-release.

Tearing the helm-release down does not tear down the daemon-set.

**Comment by tmirks** [comment]
This is not limited to deployments with helm, also a problem with regular `kubectl` deployments.

Is this intended behaviour? Should the daemonset run in the `default` namespace?

**Comment by kskewes** [comment]
I have two ...sysctl. 
I believe this has come about after doing a `helm delete --purge elasticsearch-operator` followed by a `helm install --name elasticsearch-operator` again.

**Comment by ehvattum** [comment]
@kskewes that is also a concern. If helm is not the one creatnig all resources, it can not take them down, since it depends on labels on the resources to identify what is deployed in a release.
Moving the creation of the deamonset to the chart instead of it being created by the controller should releive this issue.

**Comment by stevesloka** [comment]
Helm shouldn't do the creation, if you update the crd then the operator should update as well. I can fix the namespce problem. Also should maybe remove the helm chart, I added a nce folks wanted but seems like we have many issues due. The operator is designed to manage everything, and only needs 2 yaml to deploy.

**Comment by gianrubio** [comment]
> Helm shouldn't do the creation
Just to make it clear, the helm chart didn't create the sysctl

Besides the issue of the daemonset created in the default namespace, it's missing a deletion of the ds before the crd is deleted

**Comment by mixpix3ls** [comment]
@stevesloka Do you have the fix in a branch somewhere? Would be great to see how it was done.

**Comment by stevesloka** [comment]
An arg to specify this was added in #220. #231 aims to default this to where the operator is deployed.
