### ISSUE TITLE
Anti-affinity after pod eviction (crashed node) not adhered to

### ISSUE THREAD

**Issue by kskewes** [upmc-enterprises/elasticsearch-operator#214]
## Steps taken to Provision
1. Helm chart deploy ES operator on 3 node cluster
2. Helm chart deploy ES cluster on same 3 node cluster with 3 data pods specified
3. Data pods (D1,D2,D3) deployed onto separate nodes (N1,N2,N3 = good). 

## Steps taken on node crash. 
4. Compute node (N2) crashed. 
5. Data pod D2 recreated automatically on N3.  (Good, only 2 compute nodes at this point so no other options). 
6. N2 node restarted. 
7. D2 stays on N3. (Ok)

## Steps taken to try force recreation with node-anti-affinity.
8. N4 added to cluster. Healthy. 
9. N3 drained, D2 and D3 pods evicted. 
10. D2 and D3 both recreate onto N2. <<-- Why not one per available compute node (one at least should go on N4)?

## Extra info

I'm pretty sure that at #8 the N4 node was ready for the pods. 
I then repeated the final process by adding N5 and evicting again but those two pods D2 and D3 seem to be sticking together. 
On IBM cloud. 
Is this expected behaviour of #79 ?
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-2+231cc32d0a1119", GitCommit:"231cc32d0a111940d45936b3206548c610869df2", GitTreeState:"clean", BuildDate:"2018-04-25T08:09:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Happy to repeat any steps and grab extra logs that may be helpful. :)

**Comment by stevesloka** [comment]
The idea of the affinity is to try and separate the pods apart so you don't end up with everything on a single node. There's no specific logic in the operator to manage this, so we'll have to dig into the k8s logic to see why you're seeing that behavior.

**Comment by kskewes** [comment]
Thanks Steve. Lets close this issue then, I might open one in Kubernetes repo. 

FWIW I can see the podAntiAffinity stanza and the `role: data` label.. 

`spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - data
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
`
