### ISSUE TITLE
How can I add a plugin?

### ISSUE THREAD

**Issue by sneko** [upmc-enterprises/elasticsearch-operator#218]
I'm looking for sending notifications to Slack when errors are handled. I found a lot of documentation about setting it up but that's with X-Pack and the operator doesn't seem to manage it (required > 6.3 according to the official website).

A backup would be to use directly the plugin "watcher" as described in this article:
http://uldissturms.github.io/2016/02/08/configure-elasticsearch-error-watcher-to-send-slack-notifications/

But I'm not sure how to proceed to add a plugin and link it to ElasticSearch since I'm using the operator and its Custom Resource Definitions... Could you provide me some help please?

Thank you 😀

**Comment by sneko** [comment]
Anyone could help please?

cc @stevesloka

**Comment by stevesloka** [comment]
Hey @sneko, plugin's today are installed and baked into the image, I'm not a fan of installing deps on the fly in a production cluster. You can see those base images here: https://github.com/upmc-enterprises/docker-elasticsearch-kubernetes

**Comment by sneko** [comment]
@stevesloka oh ok I understand 👍 

I saw that 6.3 was released yesterday (https://www.elastic.co/blog/elasticsearch-6-3-0-released). How much time the operator usually takes to support new version? (It's just by curiosity, will wait the time it needs 😀  )
