### ISSUE TITLE
Make the namespace that the sysctl init daemonset is deployed into configurable?

### ISSUE THREAD

**Issue by jeromefroe** [upmc-enterprises/elasticsearch-operator#219]
Hi! I was curious if you would consider supporting making the namespace that the sysctl init daemonset is deployed into configurable? In my use case I deploy the elasticsearch operator into a dedicated namespace and it would be nice to be able to deploy the init daemonset into that same namespace instead of the default namespace. Thanks!

**Comment by sporkmonger** [comment]
Interestingly, the function to create the DaemonSet takes a namespace parameter, but then it's called with a hard-coded `"default"`:

https://github.com/upmc-enterprises/elasticsearch-operator/blob/b3a11249593f5118e83cd92b10b72841c5e87dce/pkg/controller/controller.go#L74

**Comment by stevesloka** [comment]
Closed by #220
