### ISSUE TITLE
Is there a way to setup AWS without EC2 instances?

### ISSUE THREAD

**Issue by subham-hota** [upmc-enterprises/elasticsearch-operator#222]
The cluster of our application in not in AWS but we wish to use a S3 bucket to store our snapshots , is there any other way to setup AWS for our elastic search operator without using EC2 instances(as we are not on AWS) ?

**Comment by stevesloka** [comment]
Yup you should be able to, just need to have credentials passed to auth to S3. If you get it working would be nice to PR back docs on how to setup. Happy to help further as well.

**Comment by stevesloka** [comment]
Going to close for now, please reopen if you have more questions.
