### ISSUE TITLE
Is it possible to deploy ES version 6.4?

### ISSUE THREAD

**Issue by imriss** [upmc-enterprises/elasticsearch-operator#314]
Hi,

Is it possible to deploy ES version 6.4?

Thanks

**Comment by stevesloka** [comment]
Hey @imriss, yup it's possible, we'd have to build out a new image. You can also look at @while1eq1's repo: https://github.com/while1eq1/elasticsearch-kubernetes-searchguard

**Comment by imriss** [comment]
@stevesloka thanks, is there a chance that something similar is added to the operator to have a it out of the box with the operator?

**Comment by imriss** [comment]
@stevesloka There is an issue with the certificate reported [here](https://github.com/while1eq1/elasticsearch-kubernetes-searchguard/issues/2). I faced the same issue in a fork of https://github.com/stevesloka/elasticsearch-kubernetes-searchguard

Is there any advise? Thanks
