### ISSUE TITLE
changing cron settings

### ISSUE THREAD

**Issue by ethanwinograd** [upmc-enterprises/elasticsearch-operator#36]
If I reset the cron settings in my cluster json settings, do I need to redploy the operator for those to take effect?  Is it ok to do Kubectl stop on the operator pod and get a new one that way?  not sure what ripple effects that might have..

**Comment by stevesloka** [comment]
Looks like an update to the cluster should trigger the cron to be reset. Can you check the logs of the operator after changing? The cron settings are logged to STDOUT.

**Comment by ethanwinograd** [comment]
I had to recreate the cluster for those settings to take effect... we may want to combine this issue with the other one I put in:   https://github.com/upmc-enterprises/elasticsearch-operator/issues/40

**Comment by stevesloka** [comment]
Cron updates are fixed since moving to k8s cronjobs.
