### ISSUE TITLE
restarted master nodes dont sync all data nodes

### ISSUE THREAD

**Issue by ethanwinograd** [upmc-enterprises/elasticsearch-operator#37]
running a cluster with 2 masters and 5 data nodes, when I did a manual stop on each master, they recovered to only find 3 data nodes, not the 5 which had been associated previously.  cluster health shows as green, but data is missing.

**Comment by stevesloka** [comment]
Looking at the logs from your pod, it seemed like the 2 data nodes weren't registering to the masters. After recreating your cluster it was resolved. Please re-open this if it happens again, we could look to put some node liveliness checks possibly to root out these bad pods.
