### ISSUE TITLE
Allow the Volume Reclaiming Policy to be set to Retained

### ISSUE THREAD

**Issue by splisson-altair** [upmc-enterprises/elasticsearch-operator#45]
Currently the persistent volumes created by the operator have a Reclaiming Policy = Delete , that causes them to be deleted when the PersistenVolumeClaim is released

Suggestion: add a parameter to set the value of the Reclaiming Policy

**Comment by stevesloka** [comment]
Awesome suggestion! This just came up here with my team, will get this added very soon.
