### ISSUE TITLE
es-data log4j2.properties java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by splisson-altair** [upmc-enterprises/elasticsearch-operator#47]
The cluster seemed to work fine but after a while, one of the es-data container fails to launch with the exception:
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /elasticsearch/config/repository-s3/log4j2.properties
Likely root cause: java.nio.file.AccessDeniedException: /elasticsearch/config/repository-s3/log4j2.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)

**Comment by stevesloka** [comment]
Seems like the repository-s3 plugin is the culprit there. Are you doing snapshots to s3? I haven't run into this yet. What happens if you delete the pod and let it recreate?

**Comment by splisson-altair** [comment]
Hi I'm not doing snapshot. Cluster seems stable now.

**Comment by stevesloka** [comment]
Going to close this for now, please post back if it comes up again.
