### ISSUE TITLE
network_host needs added to example deployment descriptor

### ISSUE THREAD

**Issue by ethanwinograd** [upmc-enterprises/elasticsearch-operator#82]
es-cluster.json needs to have this entry so that the nodes bind on ports other than 127.0.0.1

    "network-host": "_eth0_",

**Comment by djschny** [comment]
I would suggest against this for the following reasons:

* It no longer binds to `localhost` for use if you are running commands internally when inside the container diagnosing or scripting things
* It hard codes a particular interface

Instead I would suggest using `0.0.0.0` which will bind to any interface in the container.

**Comment by stevesloka** [comment]
That's a great point @djschny,  which one would that map to? `_site_`? 
 https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#network-interface-values

**Comment by djschny** [comment]
> which one would that map to?

Actually none of the ones listed :), hence why suggested `0.0.0.0`

**Comment by stevesloka** [comment]
Happy Monday! I tested with `_0.0.0.0_` and wondered why it wouldn't work. I'll get this updated, thanks for the feedback!
