### ISSUE TITLE
Supporting on Azure

### ISSUE THREAD

**Issue by oavioz** [upmc-enterprises/elasticsearch-operator#89]
I have a question about using this  repo on azure cloud.
 
First, dose this repo could be running on Azure?
 
If so, I see the file content “example-es-cluster.json” and my questions are:
 
•	What is “storage-class-provisioner" for azure storage? do you have an example?
•	The "zones" on spec can be for azure regions? If so do you have an example?
•	"resources" – is it per container?

Can you send please a new “example-es-cluster.json” file witch is fit to azure?
Thanks!

**Comment by stevesloka** [comment]
Hey @oavioz, I'll get an Azure k8s cluster spun up and see what needs to be changed, shouldn't be too bad. 

A 2nd PR I think we'll need to make is to enable snapshots for Azure specific since s3 isn't available (https://github.com/elastic/elasticsearch-cloud-azure).

**Comment by stevesloka** [comment]
//cc #91

**Comment by stevesloka** [comment]
@oavioz I just pushed a sample file I ran on ACS cluster and got the operator working. I'll look at the snapshotting feature next.
